SELECT Title, ACTOR.Name
FROM MOVIE
NATURAL JOIN MOVIE_ACTOR
NATURAL JOIN ACTOR
WHERE
MovieId IN(
    SELECT MovieId
    FROM MOVIE_ACTOR
    NATURAL JOIN ACTOR
    WHERE ACTOR.Name = 'Johnny Depp'
)
AND
ACTOR.Name != 'Johnny Depp'
ORDER BY Title ASC, ACTOR.Name ASC;
