UPDATE STREAM
SET Charge=4.5
WHERE CustomerId NOT IN(
  SELECT CustomerId
  FROM CUSTOMER CU JOIN COUNTRY CO ON (CU.Country=CO.Name)
  JOIN REGION USING (RegionId)
  WHERE REGION.Name='Africa'
)
AND
MovieId IN(
  SELECT MovieId
  FROM MOVIE NATURAL JOIN MOVIE_GENRE
  JOIN GENRE USING(GenreId)
  WHERE MOVIE.Year<1985 AND GENRE.Label='Sci-Fi'
)
;
