SELECT A1.Name, A2.Name, COUNT(*) AS N
FROM (ACTOR A1 NATURAL JOIN MOVIE_ACTOR MA1)
JOIN (ACTOR A2 NATURAL JOIN MOVIE_ACTOR MA2)
WHERE (MA1.MovieId = MA2.MovieId)
AND (A1.Name != A2.Name) AND (A1.Name < A2.Name)
GROUP BY A1.Name, A2.Name
HAVING N>=4
ORDER BY N DESC, A1.Name ASC, A2.Name ASC;
