SELECT S.StreamDate,M.Title,C.Name,C.Country
FROM
MOVIE M NATURAL JOIN
STREAM S NATURAL JOIN CUSTOMER C
WHERE
M.MovieId IN(
  Select MovieId
  FROM MOVIE NATURAL JOIN MOVIE_ACTOR
  NATURAL JOIN ACTOR
  WHERE ACTOR.Name='Johnny Depp'
)
AND
M.MovieId NOT IN(
  Select MovieId
  FROM MOVIE NATURAL JOIN MOVIE_ACTOR
  NATURAL JOIN ACTOR
  WHERE ACTOR.Name='Helena Bonham Carter'
)
AND
C.Country!='China'
ORDER BY S.StreamDate DESC
LIMIT 15;
