SELECT M.Title,R.Name,COUNT(STREAM.StreamDate)
FROM (MOVIE M,REGION R) LEFT OUTER JOIN (STREAM NATURAL JOIN CUSTOMER JOIN COUNTRY)
ON (M.MovieId=STREAM.MovieId AND CUSTOMER.Country=COUNTRY.Name AND COUNTRY.RegionId=R.RegionId)
WHERE M.Title LIKE '%war%'
GROUP BY M.Title,R.Name
ORDER BY M.Title ASC,R.Name ASC;
